<?php

namespace Database\Seeders;

use App\Models\Market\Meme;
use App\Models\User;
use App\Models\Market\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class MemeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $memes = [
            [
                'id' => 1,
                'creator_id' => 2,
                'category_id' => 3,
                'title' => 'HTML Pain',
                'ticker' => 'NOHTML',
                'image_path' => 'meme1.jpeg',
                'text_alt' => 'Uomo che simula un infarto. Testo: HTML è un linguaggio di programmazione. Ogni volta che viene detta questa frase un programmatore muore.',
                'base_price' => 2.5,
                'slope' => 0.015,
                'current_price' => 2.55,
                'circulating_supply' => 450,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:00:00',
                'approved_by' => 1,
                'created_at' => '2026-01-06 17:00:00',
                'updated_at' => '2026-01-06 17:00:00',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'creator_id' => 5,
                'category_id' => 3,
                'title' => 'Magic Code',
                'ticker' => 'IT_RUN',
                'image_path' => 'meme2.jpeg',
                'text_alt' => 'Scena di Fight Club. Testo: Prima regola dell informatica: non chiedersi perché qualcosa funziona.',
                'base_price' => 3.1,
                'slope' => 0.0015,
                'current_price' => 3.25,
                'circulating_supply' => 600,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:05:00',
                'approved_by' => 3,
                'created_at' => '2026-01-06 17:05:00',
                'updated_at' => '2026-01-06 17:05:00',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'creator_id' => 1,
                'category_id' => 3,
                'title' => 'Cat Cache',
                'ticker' => 'COOKIES',
                'image_path' => 'meme3.jpeg',
                'text_alt' => 'Gatto incastrato dentro il case di un computer. Testo: Avevo messo i miei cookies qui, qualcuno li ha cancellati.',
                'base_price' => 1.8,
                'slope' => 0.003,
                'current_price' => 2.1,
                'circulating_supply' => 90,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:10:00',
                'approved_by' => 2,
                'created_at' => '2026-01-06 17:10:00',
                'updated_at' => '2026-01-06 17:10:00',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'creator_id' => 4,
                'category_id' => 1,
                'title' => 'Exam Wall',
                'ticker' => 'WALL',
                'image_path' => 'meme.jpeg',
                'text_alt' => 'Ragazza che piange spiegando cose vs donna che fissa il vuoto. Testo: Io che cerco di spiegare gli argomenti al muro.',
                'base_price' => 1.2,
                'slope' => 0.012,
                'current_price' => 1.22,
                'circulating_supply' => 800,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:15:00',
                'approved_by' => 5,
                'created_at' => '2026-01-06 17:15:00',
                'updated_at' => '2026-01-06 17:15:00',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'creator_id' => 3,
                'category_id' => 9,
                'title' => 'Vet Escape',
                'ticker' => 'VET_NO',
                'image_path' => 'meme4.jpg',
                'text_alt' => 'Gatto nascosto dietro una porta che fa il dito medio. Testo: Micio dove sei? Dobbiamo andare dal veterinario.',
                'base_price' => 4.0,
                'slope' => 0.005,
                'current_price' => 4.8,
                'circulating_supply' => 150,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:20:00',
                'approved_by' => 6,
                'created_at' => '2026-01-06 17:20:00',
                'updated_at' => '2026-01-06 17:20:00',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'creator_id' => 6,
                'category_id' => 5,
                'title' => 'Work Force',
                'ticker' => 'L_EQ_FS',
                'image_path' => 'meme5.jpeg',
                'text_alt' => 'Enrico Fermi alla lavagna. Testo: Quando ti dicono di trovare lavoro ma conosci solo L=F*S.',
                'base_price' => 2.9,
                'slope' => 0.0025,
                'current_price' => 3.0,
                'circulating_supply' => 420,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:25:00',
                'approved_by' => 1,
                'created_at' => '2026-01-06 17:25:00',
                'updated_at' => '2026-01-06 17:25:00',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'creator_id' => 2,
                'category_id' => 11,
                'title' => 'Ecopass',
                'ticker' => 'ECO_OK',
                'image_path' => 'meme5.jpg',
                'text_alt' => 'Kevin Durant che piange commosso. Testo: Questi saremo noi quando racconteremo la nostra prima sufficienza in Economia Aziendale.',
                'base_price' => 3.5,
                'slope' => 0.002,
                'current_price' => 3.75,
                'circulating_supply' => 550,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:30:00',
                'approved_by' => 4,
                'created_at' => '2026-01-06 17:30:00',
                'updated_at' => '2026-01-06 17:30:00',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'creator_id' => 5,
                'category_id' => 8,
                'title' => 'Anatomy Trap',
                'ticker' => 'ANATMY',
                'image_path' => 'meme4.jpeg',
                'text_alt' => 'Joker con cartello "Dopo Anatomia è tutto in discesa" investito da un camion.',
                'base_price' => 5.0,
                'slope' => 0.004,
                'current_price' => 6.2,
                'circulating_supply' => 100,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:35:00',
                'approved_by' => 3,
                'created_at' => '2026-01-06 17:35:00',
                'updated_at' => '2026-01-06 17:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'creator_id' => 1,
                'category_id' => 14,
                'title' => 'Hegel Hell',
                'ticker' => 'HEGEL',
                'image_path' => 'meme7.jpeg',
                'text_alt' => 'Mr Incredible uncanny. Felice: Quelli che amano Hegel. Triste: Studenti che scoprono 4 mila pagine manoscritte.',
                'base_price' => 1.5,
                'slope' => 0.001,
                'current_price' => 1.55,
                'circulating_supply' => 900,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:40:00',
                'approved_by' => 2,
                'created_at' => '2026-01-06 17:40:00',
                'updated_at' => '2026-01-06 17:40:00',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'creator_id' => 4,
                'category_id' => 10,
                'title' => 'Law Suit',
                'ticker' => 'MUTUO',
                'image_path' => 'meme6.jpg',
                'text_alt' => 'DiCaprio Gatsby con calice. Testo: Subisco un tamponamento e pretendo che il risarcimento estingua il mutuo.',
                'base_price' => 4.2,
                'slope' => 0.0035,
                'current_price' => 4.9,
                'circulating_supply' => 250,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:45:00',
                'approved_by' => 5,
                'created_at' => '2026-01-06 17:45:00',
                'updated_at' => '2026-01-06 17:45:00',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'creator_id' => 3,
                'category_id' => 15,
                'title' => 'Et Tu Brute',
                'ticker' => 'BRUTO',
                'image_path' => 'meme8.jpeg',
                'text_alt' => 'Confronto: Delusione d amore vs Tradimento di Bruto (dipinto morte di Cesare).',
                'base_price' => 2.1,
                'slope' => 0.0022,
                'current_price' => 2.3,
                'circulating_supply' => 330,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:50:00',
                'approved_by' => 6,
                'created_at' => '2026-01-06 17:50:00',
                'updated_at' => '2026-01-06 17:50:00',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'creator_id' => 6,
                'category_id' => 14,
                'title' => 'Sokrates',
                'ticker' => 'IDK_X2',
                'image_path' => 'meme9.png',
                'text_alt' => 'Mr Incredible felice vs Socrate serio. Testo: Persone che non sanno vs Persone che sanno di non sapere.',
                'base_price' => 2.8,
                'slope' => 0.0018,
                'current_price' => 2.95,
                'circulating_supply' => 400,
                'status' => 'approved',
                'approved_at' => '2026-01-06 17:55:00',
                'approved_by' => 1,
                'created_at' => '2026-01-06 17:55:00',
                'updated_at' => '2026-01-06 17:55:00',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'creator_id' => 2,
                'category_id' => 13,
                'title' => 'Holmes Back',
                'ticker' => 'DOYLE',
                'image_path' => 'meme.webp',
                'text_alt' => 'Meme Star Wars. Testo: Arthur Conan Doyle in 1903: Somehow, Sherlock Holmes returned.',
                'base_price' => 1.9,
                'slope' => 0.0015,
                'current_price' => 2.0,
                'circulating_supply' => 650,
                'status' => 'approved',
                'approved_at' => '2026-01-06 18:00:00',
                'approved_by' => 4,
                'created_at' => '2026-01-06 18:00:00',
                'updated_at' => '2026-01-06 18:00:00',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'creator_id' => 5,
                'category_id' => 19,
                'title' => 'Dino Comm',
                'ticker' => 'MEREND',
                'image_path' => 'meme12.jpeg',
                'text_alt' => 'Due dinosauri che ridono sguaiatamente. Testo: Ah sei laureato in scienze della comunicazione? Scienze delle merendine.',
                'base_price' => 1.1,
                'slope' => 0.0005,
                'current_price' => 1.15,
                'circulating_supply' => 950,
                'status' => 'approved',
                'approved_at' => '2026-01-06 18:05:00',
                'approved_by' => 3,
                'created_at' => '2026-01-06 18:05:00',
                'updated_at' => '2026-01-06 18:05:00',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'creator_id' => 1,
                'category_id' => 6,
                'title' => 'Archi Sleep',
                'ticker' => 'ZOMBIE',
                'image_path' => 'meme10.jpeg',
                'text_alt' => 'Tom Cruise confuso. Testo: Quando scopri che esistono studenti di Architettura che non hanno mai fatto nottate. Questa non può essere la realtà.',
                'base_price' => 3.8,
                'slope' => 0.003,
                'current_price' => 4.1,
                'circulating_supply' => 200,
                'status' => 'approved',
                'approved_at' => '2026-01-06 18:10:00',
                'approved_by' => 2,
                'created_at' => '2026-01-06 18:10:00',
                'updated_at' => '2026-01-06 18:10:00',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'creator_id' => 3,
                'category_id' => 1,
                'title' => 'Easy Exam',
                'ticker' => 'ARG_OK',
                'image_path' => 'meme14.jpeg',
                'text_alt' => 'Gatto con espressione furbetta. Testo: Prof: parla pure di un argomento a scelta..',
                'base_price' => 2.7,
                'slope' => 0.0021,
                'current_price' => 2.85,
                'circulating_supply' => 500,
                'status' => 'approved',
                'approved_at' => '2026-01-06 18:15:00',
                'approved_by' => 6,
                'created_at' => '2026-01-06 18:15:00',
                'updated_at' => '2026-01-06 18:15:00',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'creator_id' => 4,
                'category_id' => 1,
                'title' => 'Winter Bed',
                'ticker' => 'BED_WIN',
                'image_path' => 'meme13.jpeg',
                'text_alt' => 'Vignetta di una persona che fa tutto rimanendo nel letto a causa del freddo invernale.',
                'base_price' => 3.3,
                'slope' => 0.0019,
                'current_price' => 3.45,
                'circulating_supply' => 620,
                'status' => 'approved',
                'approved_at' => '2026-01-06 18:20:00',
                'approved_by' => 5,
                'created_at' => '2026-01-06 18:20:00',
                'updated_at' => '2026-01-06 18:20:00',
                'deleted_at' => null,
            ],
        ];

        foreach ($memes as $memeData) {
            Meme::create($memeData);
        }
    }
}
